name: datasource
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  aws_dynamodb_api: ^2.0.0
  domain:
    git: https://github.com/minia68/mv-tr__domain.git

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
